package POJOS;
// Generated 07-jun-2022 17:24:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private int deptNo;
     private String nombre;
     private String ubicacion;
     private Integer presupuesto;
     private Set<Empleados> empleadoses = new HashSet<Empleados>(0);

    public Departamentos() {
    }

    @Override
    public String toString() {
        return "Departamentos{" + "deptNo=" + deptNo + ", nombre=" + nombre + ", ubicacion=" + ubicacion + ", presupuesto=" + presupuesto + ", empleadoses=" + empleadoses + '}';
    }

	
    public Departamentos(int deptNo) {
        this.deptNo = deptNo;
    }
    public Departamentos(int deptNo, String nombre, String ubicacion, Integer presupuesto, Set<Empleados> empleadoses) {
       this.deptNo = deptNo;
       this.nombre = nombre;
       this.ubicacion = ubicacion;
       this.presupuesto = presupuesto;
       this.empleadoses = empleadoses;
    }
   
    public int getDeptNo() {
        return this.deptNo;
    }
    
    public void setDeptNo(int deptNo) {
        this.deptNo = deptNo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public Integer getPresupuesto() {
        return this.presupuesto;
    }
    
    public void setPresupuesto(Integer presupuesto) {
        this.presupuesto = presupuesto;
    }
    public Set<Empleados> getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set<Empleados> empleadoses) {
        this.empleadoses = empleadoses;
    }




}


