package POJOS;
// Generated 07-jun-2022 17:24:26 by Hibernate Tools 4.3.1



/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private String empNo;
     private Departamentos departamentos;
     private String nombre;
     private Integer alta;
     private Integer salario;

    public Empleados() {
    }

    @Override
    public String toString() {
        return "Empleados{" + "empNo=" + empNo + ", departamentos=" + departamentos + ", nombre=" + nombre + ", alta=" + alta + ", salario=" + salario + '}';
    }

	
    public Empleados(String empNo, Departamentos departamentos) {
        this.empNo = empNo;
        this.departamentos = departamentos;
    }
    public Empleados(String empNo, Departamentos departamentos, String nombre, Integer alta, Integer salario) {
       this.empNo = empNo;
       this.departamentos = departamentos;
       this.nombre = nombre;
       this.alta = alta;
       this.salario = salario;
    }
   
    public String getEmpNo() {
        return this.empNo;
    }
    
    public void setEmpNo(String empNo) {
        this.empNo = empNo;
    }
    public Departamentos getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getAlta() {
        return this.alta;
    }
    
    public void setAlta(Integer alta) {
        this.alta = alta;
    }
    public Integer getSalario() {
        return this.salario;
    }
    
    public void setSalario(Integer salario) {
        this.salario = salario;
    }




}


